package nl.djj.swgoh_bot_v2.helpers;

import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.entities.MessageEmbed;
import nl.djj.swgoh_bot_v2.config.Config;
import nl.djj.swgoh_bot_v2.entities.SwgohProfile;

import java.awt.*;
import java.time.ZonedDateTime;

/**
 * @author DJJ
 */
//CHECKSTYLE.OFF: MultipleStringLiteralsCheck
public final class MessageFormatter {
    /**
     * Constructor.
     */
    private MessageFormatter() {
        super();
    }

    private static MessageEmbed baseEmbed() {
        final EmbedBuilder builder = new EmbedBuilder();
        builder.setAuthor(Config.BOT_NAME, "https://www.youtube.com/watch?v=YddwkMJG1Jo", "https://cdn.discordapp.com/avatars/405842805441822721/83e13c25144df2db31aa963083e6dc40.png");
        builder.setColor(new Color(Config.BOT_COLOUR));
        builder.setTimestamp(ZonedDateTime.now());
        builder.setFooter("Generated by: " + Config.BOT_NAME);
        return builder.build();
    }

    /**
     * Formats the info to an embed.
     * @param profile the profile.
     * @return a message embed.
     */
    public static MessageEmbed formatSwgohProfile(final SwgohProfile profile) {
        final EmbedBuilder builder = new EmbedBuilder(baseEmbed());
        builder.appendDescription("Generic Profile info for: " + profile.getName());
        final String generic = String.format("%-15s%-15s%n", "Level = ", profile.getLevel()) +
                String.format("%-15s%-15s%n", "Guild = ", profile.getGuild());
        builder.addField(new MessageEmbed.Field("generic", "```" + generic + "```", false));
        final String gp = String.format("%-15s%-15s%n", "GP_total = ", profile.getGpTotal()) +
                String.format("%-15s%-15s%n", "GP_toons = ", profile.getGpToons()) +
                String.format("%-15s%-15s%n", "GP_ships = ", profile.getGpShips());
        builder.addField(new MessageEmbed.Field("GP", "```" + gp + "```", false));
        final String arena = String.format("%-15s%-15s%n", "Toon Arena = ", profile.getToonRank()) +
                String.format("%-15s%-15s%n", "Ship Arena = ", profile.getShipRank());
        builder.addField(new MessageEmbed.Field("Arena", "```" + arena + "```", false));
        final String profileLink = String.format("%-15s%-15s%n", "SWGOH ", "[Profile](" + profile.getProfileUrl() + ")");
        builder.addField(new MessageEmbed.Field("SWGOH", profileLink, false));
        return builder.build();
    }
    //CHECKSTYLE.ON: MultipleStringLiteralsCheck
}
